---
- hosts: leaf1a
  connection: local
  gather_facts: yes 
  vars_files:
  - "group_vars/all.yaml"  

  tasks:

  - name: SCP files to the switch
    shell: scp /vagrant/scripts/{{ item }} vagrant@{{ inventory_hostname }}:/mnt/flash
    with_items:
     - startup.sh
     - salt-eos-latest.swix

  - name: 




