---
- hosts: leafs
  connection: local
  gather_facts: yes 
  vars_files:
  - "group_vars/all.yaml"  

  tasks:

  - name: Configure Arista Vlans
    eos_config:
      src: vlans.j2
      provider: "{{ eos_connection }}"
