---

- hosts: base_lab_Leaf1
  connection: httpapi
  gather_facts: yes
  vars_files:
    - "../vars/all.yaml"

  tasks:
    - name: configure access lists
      eos_config:
        src: ../templates/jpmc_acl.j2
        defaults: true
      tags:
        - acl
      #when:
        #- (access_lists is defined) and (access_lists|length > 0)
        #- (device_access_lists is defined) and (device_access_lists|length > 0)
