---

- hosts: all
  connection: httpapi
  gather_facts: yes
  
  tasks:
    - name: show running config
      eos_command:
       commands: "show running-config"
      register: backup

    - name: backup running config
      copy:
        content: "{{ backup.stdout[0] }}"
        dest: "./files/{{ inventory_hostname }}.cfg"
