---

- hosts: leaf1b
  connection: local
  gather_facts: yes 
  vars_files:
  - "vars/all.yaml"

  tasks:
  - name: BGP on leaf switches
    eos_config:
      src: templates/bgp_leaf.j2
      provider: "{{ eos_connection }}"
    ignore_errors: True

  - name: Connectivity checker
    eos_command:
      commands:
        - ping {{ item }}
      provider: '{{ eos_connection }}'
    register: result
    with_items: "{{ ebgp_peers[inventory_hostname].keys() }}"    

  - name: Check the pings from point to point links
    debug: var=result
