---

- hosts: base-lab_Leaf1
  connection: httpapi
  gather_facts: yes
  vars_files:
  - "../vars/all.yaml"

  tasks:
  - name: BGP on leaf switches
    eos_config:
      src: ../templates/bgp_leaf.j2
    ignore_errors: True
