- name: Write facts to disk using a template
        copy:
        content: |
          #jinja2: lstrip_blocks: True
          EOS device info:
            {% for host in groups['leafs'] %}
            Hostname: {{ hostvars[host].ansible_net_version }}
            Version: {{ hostvars[host].ansible_net_version }}
            Model: {{ hostvars[host].ansible_net_model }}
            Serial: {{ hostvars[host].ansible_net_serialnum }}
            {% endfor %}
        dest: /vagrant/scripts/ansible/facts/
      run_once: yes
