---

- hosts: switches
  connection: local
  gather_facts: no
  vars_files:
  - "vars/all.yaml"  

  tasks:

  - name: Add Shell user, unix protocol and eventhandler for reboots
    eos_config:
       src: templates/salt.j2         
       provider: "{{ eos_connection }}"

  - name: install swix and startup.sh
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    connection: ssh
    remote_user: ansible
    become: yes
    with_items:
    - { src: ./salt-eos-latest.swix , dest: /mnt/flash , mode: 0777}
    - { src: ./startup.sh , dest: /mnt/flash , mode: 0777}

  - name: Copy boot extensions
    shell: "{{ item }}"
    with_items:
      - 'FastCli -p 15 -c "copy flash:salt-eos-latest.swix extension:"'
      - 'FastCli -p 15 -c "extension salt-eos-latest.swix force"'
      - 'FastCli -p 15 -c "copy installed-extensions boot-extensions"'
    connection: ssh
    remote_user: ansible
    become: yes

  - name: install start via startup shell script.
    shell: "{{ item }}"
    with_items:
      - sleep 10
      - sudo /mnt/flash/startup.sh
    connection: ssh
    remote_user: ansible
    become: yes
